{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T16:53:42.190Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T16:53:50.127Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T16:54:07.937Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T16:54:38.087Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T16:56:27.597Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T16:56:58.488Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T16:57:24.549Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:00:17.431Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:00:31.192Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:04:46.069Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:04:59.917Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:05:32.861Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:05:32.916Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:05:46.942Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:05:58.166Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:08:17.524Z"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"siva\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":100,"line":"326","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"siva\"\n    at Client._connectionCallback (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:327:19)\n    at Client._handleErrorMessage (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\client.js:347:19)\n    at Connection.emit (node:events:520:28)\n    at C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg\\lib\\connection.js:117:12\n    at Parser.parse (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\SIVA\\OneDrive\\projects\\Management\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2024-07-13T17:10:10.315Z"}
{"error":"User.findAll is not a function","level":"error","message":"Error fetching users","timestamp":"2024-07-13T17:16:00.517Z"}
{"error":"User.findAll is not a function","level":"error","message":"Error fetching users","timestamp":"2024-07-13T17:16:56.336Z"}
{"error":"User.findAll is not a function","level":"error","message":"Error fetching users","timestamp":"2024-07-13T17:17:26.804Z"}
{"error":"User.create is not a function","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:20:21.056Z"}
{"error":"User.create is not a function","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:21:29.493Z"}
{"error":"User.create is not a function","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:21:40.096Z"}
{"error":"User.create is not a function","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:21:58.869Z"}
{"error":"User.create is not a function","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:24:27.247Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:27:07.211Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:28:33.286Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:28:44.348Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:29:19.432Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:29:37.482Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:34:32.921Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:40:05.155Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:40:53.168Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:40:58.222Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:41:02.016Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:41:37.049Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:45:07.388Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:46:52.360Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:48:32.312Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:48:37.836Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:48:49.077Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:48:50.862Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:48:58.753Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:49:00.024Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:49:13.820Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:51:01.324Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:53:25.447Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:54:00.517Z"}
{"error":[{"context":{"child":"name","key":"name","label":"name","value":"sivaFF"},"message":"\"name\" is not allowed","path":["name"],"type":"object.unknown"}],"level":"error","message":"Validation error","timestamp":"2024-07-13T17:54:04.518Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:54:46.809Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:54:58.206Z"}
{"error":[{"context":{"child":"name","key":"name","label":"name","value":"sivaFF"},"message":"\"name\" is not allowed","path":["name"],"type":"object.unknown"}],"level":"error","message":"Validation error","timestamp":"2024-07-13T17:54:59.775Z"}
{"error":[{"context":{"child":"name","key":"name","label":"name","value":"sivaFF"},"message":"\"name\" is not allowed","path":["name"],"type":"object.unknown"}],"level":"error","message":"Validation error","timestamp":"2024-07-13T17:55:04.681Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:55:32.842Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:55:44.490Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:55:47.497Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:56:12.109Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T17:56:20.748Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T17:56:21.917Z"}
{"error":[{"context":{"child":"name","key":"name","label":"name","value":"sivaFF"},"message":"\"name\" is not allowed","path":["name"],"type":"object.unknown"}],"level":"error","message":"Validation error","timestamp":"2024-07-13T17:57:00.870Z"}
{"error":"notNull Violation: User.data cannot be null","level":"error","message":"Error creating user","timestamp":"2024-07-13T18:01:51.515Z"}
{"error":[{"context":{"child":"name","key":"name","label":"name","value":"sivaFF"},"message":"\"name\" is not allowed","path":["name"],"type":"object.unknown"}],"level":"error","message":"Validation error","timestamp":"2024-07-13T18:02:16.406Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T18:03:20.289Z"}
{"level":"info","message":"User created successfully","timestamp":"2024-07-13T18:03:21.245Z","user":{"createdAt":"2024-07-13T18:03:21.239Z","data":{"email":"sivaFF@gmail.com","name":"sivaFF","password":"password123"},"id":1,"updatedAt":"2024-07-13T18:03:21.239Z"}}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T18:03:36.307Z"}
{"level":"info","message":"Server is running on port 3000","timestamp":"2024-07-13T18:04:23.280Z"}
